apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp2-ingress
  annotations:
    nginx.org/access-control-policy: |
      {
        "allow":["10.0.0.0/8"]
      }
spec:
  ingressClassName: nginx
  rules:
  - host: webapp2.example.com
    http:
      paths:
      - path: /tea
        pathType: Prefix
        backend:
          service:
            name: tea-svc
            port:
              number: 80
      - path: /coffee
        pathType: Prefix
        backend:
          service:
            name: coffee-svc
            port:
              number: 80
